version: '3.1'

volumes:
   mariadb_data: {}

networks:
  htp-net:

services:
  web:
    image: nginx:latest
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - .:/app
        - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
          #- ./data/certbot/conf:/etc/letsencrypt
          #- ./data/certbot/www:/var/www/certbot
    networks:
        - htp-net
    deploy:
        mode: global 

  htp:
    image: hashcat/htp
    volumes:
        - ./docker/php-set-upload.conf:/usr/local/etc/php-fpm.d/php-set-upload.conf
        - ./docker/php-set-max-upload.conf:/usr/local/etc/php/conf.d/php-set-max-upload.conf
        - ./docker/php.ini-production:/usr/local/etc/php/php.ini-production
        - ./docker/php.ini-development:/usr/local/etc/php/php.ini-development
    environment:
        PHP.memory_limit: "2G"
        PHP.upload_max_filesize: "20G"
        PHP.post_max_size: "20G"
    networks:
        - htp-net
    depends_on:
        - mariadb
    deploy:
        mode: global

  mariadb:
    image: mariadb:latest
    volumes:
        - mariadb_data:/var/lib/mysql/
    environment:
        MYSQL_ROOT_PASSWORD: "hashcat123"
    networks:
        - htp-net
    deploy:
        mode: global

        #certbot:
        #image: certbot/certbot
        #volumes:
        #- ./data/certbot/conf:/etc/letsencrypt
        #- ./data/certbot/www:/var/www/certbot
