version: '3.1'

volumes:
   mariadb_data: {}

networks:
  htp-net:

services:
  web:
    image: nginx:latest
    ports:
        - "8088:80"
    volumes:
        - .:/app
        - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
        - htp-net
    deploy:
        mode: global 

  htp:
    image: hashcat/htp
    environment:
        PHP.memory_limit: "2G"
        PHP.upload_max_filesize: "2G"
        PHP.post_max_size: "2G"
    networks:
        - htp-net
    deploy:
        mode: global

  mariadb:
    image: mariadb:latest
    volumes:
        - mariadb_data:/var/lib/mysql/
    environment:
        MYSQL_ROOT_PASSWORD: "hashcat123"
    networks:
        - htp-net
    deploy:
        mode: global

